CREATE TABLE IF NOT EXISTS spaces (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,name TEXT NOT NULL,slug TEXT NOT NULL,description TEXT,enable_computer INTEGER NOT NULL DEFAULT 0,workspace_image TEXT,runtime_node_id TEXT,workspace_kind TEXT NOT NULL DEFAULT 'local',workspace_status TEXT NOT NULL DEFAULT 'ready',config_json TEXT NOT NULL DEFAULT '{}',last_error TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(tenant_id,slug));
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS agents (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,space_id TEXT NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,name TEXT NOT NULL,slug TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',enable_memory INTEGER NOT NULL DEFAULT 1,memory_provider_id TEXT,config_json TEXT NOT NULL DEFAULT '{}',last_error TEXT,avatar_color TEXT,avatar_shape TEXT,avatar_url TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(tenant_id,space_id,slug));
-- statement-breakpoint
CREATE INDEX IF NOT EXISTS agents_tenant_idx ON agents(tenant_id,created_at);
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS cloud_agent_sessions (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,agent_id TEXT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,title TEXT NOT NULL DEFAULT '新对话',status TEXT NOT NULL DEFAULT 'active',kind TEXT NOT NULL DEFAULT 'chat',project TEXT,origin_json TEXT NOT NULL DEFAULT '{}',model TEXT,model_route_id TEXT,reasoning TEXT,draft_text TEXT NOT NULL DEFAULT '',created_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,last_seq INTEGER NOT NULL DEFAULT 0,active_run_id TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS cloud_agent_events (id TEXT PRIMARY KEY,session_id TEXT NOT NULL REFERENCES cloud_agent_sessions(id) ON DELETE CASCADE,seq INTEGER NOT NULL,type TEXT NOT NULL,run_id TEXT,payload_json TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL,UNIQUE(session_id,seq));
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS cloud_agent_runs (id TEXT PRIMARY KEY,session_id TEXT NOT NULL REFERENCES cloud_agent_sessions(id) ON DELETE CASCADE,status TEXT NOT NULL,cancel_requested INTEGER NOT NULL DEFAULT 0,error TEXT,started_at TEXT,completed_at TEXT,created_at TEXT NOT NULL);
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS agent_schedules (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,agent_id TEXT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,name TEXT NOT NULL,description TEXT,pattern TEXT,trigger_kind TEXT NOT NULL DEFAULT 'schedule',listener_json TEXT NOT NULL DEFAULT '{}',webhook_secret TEXT,prompt TEXT NOT NULL,project TEXT,enabled INTEGER NOT NULL DEFAULT 1,max_runs INTEGER,run_count INTEGER NOT NULL DEFAULT 0,timezone TEXT NOT NULL DEFAULT 'UTC',next_run_at TEXT,last_run_at TEXT,last_status TEXT,last_error TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS agent_heartbeats (agent_id TEXT PRIMARY KEY REFERENCES agents(id) ON DELETE CASCADE,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,enabled INTEGER NOT NULL DEFAULT 0,interval_minutes INTEGER NOT NULL DEFAULT 60,prompt TEXT,next_run_at TEXT,last_run_at TEXT,last_status TEXT,last_error TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS agent_automation_runs (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,agent_id TEXT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,kind TEXT NOT NULL,schedule_id TEXT REFERENCES agent_schedules(id) ON DELETE SET NULL,session_id TEXT REFERENCES cloud_agent_sessions(id) ON DELETE SET NULL,cloud_run_id TEXT REFERENCES cloud_agent_runs(id) ON DELETE SET NULL,status TEXT NOT NULL,prompt TEXT,result_text TEXT,error TEXT,started_at TEXT,completed_at TEXT,created_at TEXT NOT NULL);
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS agent_user_questions (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,agent_id TEXT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,session_id TEXT NOT NULL,run_id TEXT,tool_call_id TEXT,question TEXT NOT NULL,options_json TEXT NOT NULL DEFAULT '[]',allow_multiple INTEGER NOT NULL DEFAULT 0,secret INTEGER NOT NULL DEFAULT 0,mode TEXT NOT NULL DEFAULT 'sync',timeout_seconds INTEGER,timeout_action TEXT NOT NULL DEFAULT 'skip',default_option_ids_json TEXT NOT NULL DEFAULT '[]',placeholder TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'pending',answer_json TEXT NOT NULL DEFAULT '{}',expires_at TEXT,resolved_at TEXT,created_at TEXT NOT NULL);
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS agent_tool_approvals (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,agent_id TEXT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,session_id TEXT NOT NULL,run_id TEXT,tool_call_id TEXT,tool_name TEXT NOT NULL,qualified_name TEXT,args_json TEXT NOT NULL DEFAULT '{}',reason TEXT NOT NULL DEFAULT 'policy_ask',ai_json TEXT NOT NULL DEFAULT '{}',status TEXT NOT NULL DEFAULT 'pending',decided_by TEXT,always_allow INTEGER NOT NULL DEFAULT 0,expires_at TEXT,resolved_at TEXT,created_at TEXT NOT NULL);
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS model_upstreams (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,name TEXT NOT NULL,slug TEXT NOT NULL,protocol TEXT NOT NULL,config_json TEXT NOT NULL DEFAULT '{}',status TEXT NOT NULL DEFAULT 'ready',last_error TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(tenant_id,slug));
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS upstream_models (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,upstream_id TEXT NOT NULL REFERENCES model_upstreams(id) ON DELETE CASCADE,native_model TEXT NOT NULL,canonical_model TEXT NOT NULL,display_name TEXT,capability TEXT NOT NULL,weight TEXT NOT NULL DEFAULT '100',is_default INTEGER NOT NULL DEFAULT 0,options_json TEXT NOT NULL DEFAULT '{}',meta_json TEXT NOT NULL DEFAULT '{}',status TEXT NOT NULL DEFAULT 'ready',last_error TEXT,synced_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(tenant_id,upstream_id,native_model,capability));
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS model_routes (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,name TEXT NOT NULL,slug TEXT NOT NULL,capability TEXT NOT NULL,alias TEXT,upstream_id TEXT NOT NULL REFERENCES model_upstreams(id) ON DELETE CASCADE,model TEXT NOT NULL,options_json TEXT NOT NULL DEFAULT '{}',priority TEXT NOT NULL DEFAULT '100',weight TEXT NOT NULL DEFAULT '100',is_default INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'ready',last_error TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(tenant_id,slug));
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS memory_providers (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,name TEXT NOT NULL,slug TEXT NOT NULL,kind TEXT NOT NULL,config_json TEXT NOT NULL DEFAULT '{}',secret_json TEXT NOT NULL DEFAULT '{}',enabled INTEGER NOT NULL DEFAULT 1,is_default INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'ready',last_error TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(tenant_id,slug));
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS component_instances (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,agent_id TEXT REFERENCES agents(id) ON DELETE CASCADE,component_type TEXT NOT NULL,component_ref TEXT NOT NULL,name TEXT NOT NULL,config_json TEXT NOT NULL DEFAULT '{}',secret_json TEXT NOT NULL DEFAULT '{}',status TEXT NOT NULL DEFAULT 'ready',last_error TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS memories (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,instance_id TEXT REFERENCES component_instances(id) ON DELETE CASCADE,provider_id TEXT REFERENCES memory_providers(id) ON DELETE SET NULL,agent_id TEXT REFERENCES agents(id) ON DELETE CASCADE,user_id TEXT,layer TEXT NOT NULL DEFAULT 'fact',content TEXT NOT NULL,tags_json TEXT NOT NULL DEFAULT '[]',pinned INTEGER NOT NULL DEFAULT 0,importance TEXT NOT NULL DEFAULT '3',source TEXT NOT NULL DEFAULT 'manual',metadata_json TEXT NOT NULL DEFAULT '{}',embedding TEXT,embedding_model TEXT,embedding_dim INTEGER,content_hash TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS memory_edges (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,agent_id TEXT REFERENCES agents(id) ON DELETE CASCADE,from_memory_id TEXT NOT NULL REFERENCES memories(id) ON DELETE CASCADE,to_memory_id TEXT NOT NULL REFERENCES memories(id) ON DELETE CASCADE,relation TEXT NOT NULL DEFAULT 'related',weight TEXT NOT NULL DEFAULT '1',created_at TEXT NOT NULL,UNIQUE(from_memory_id,to_memory_id,relation),UNIQUE(tenant_id,agent_id,from_memory_id,to_memory_id,relation));
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS skills (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,name TEXT NOT NULL,title TEXT NOT NULL DEFAULT '',description TEXT NOT NULL DEFAULT '',version TEXT,builtin INTEGER NOT NULL DEFAULT 0,source_json TEXT NOT NULL DEFAULT '{}',homepage TEXT,license TEXT,files_json TEXT NOT NULL DEFAULT '[]',file_count INTEGER NOT NULL DEFAULT 0,size_bytes INTEGER NOT NULL DEFAULT 0,repo_key TEXT,auto_update INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(tenant_id,name));
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS agent_skills (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,agent_id TEXT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,skill_id TEXT NOT NULL REFERENCES skills(id) ON DELETE CASCADE,name TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 1,path TEXT NOT NULL,version TEXT,status TEXT NOT NULL DEFAULT 'installed',error TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(agent_id,name));
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS mcp_policies (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,agent_id TEXT REFERENCES agents(id) ON DELETE CASCADE,name TEXT NOT NULL,policy_json TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS provider_catalog (id TEXT PRIMARY KEY,name TEXT NOT NULL,kind TEXT NOT NULL,manifest_json TEXT NOT NULL DEFAULT '{}',enabled INTEGER NOT NULL DEFAULT 1,updated_at TEXT NOT NULL);
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS integration_packages (id TEXT PRIMARY KEY,slug TEXT NOT NULL UNIQUE,name TEXT NOT NULL,description TEXT,manifest_json TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS integration_components (id TEXT PRIMARY KEY,package_id TEXT NOT NULL REFERENCES integration_packages(id) ON DELETE CASCADE,ref TEXT NOT NULL,kind TEXT NOT NULL,manifest_json TEXT NOT NULL DEFAULT '{}',UNIQUE(package_id,ref));
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS connector_auth_profiles (id TEXT PRIMARY KEY,scope_key TEXT NOT NULL,profile_key TEXT NOT NULL,label TEXT NOT NULL DEFAULT '',kind TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 0,config_enc TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(scope_key,profile_key));
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS connector_settings (id TEXT PRIMARY KEY,scope_key TEXT NOT NULL,connector_ref TEXT NOT NULL,config_enc TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(scope_key,connector_ref));
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS agent_connector_installations (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,agent_id TEXT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,connector_ref TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 1,config_enc TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(agent_id,connector_ref));
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS channel_events (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,provider TEXT NOT NULL,external_id TEXT NOT NULL,payload_json TEXT NOT NULL,delivery_status TEXT NOT NULL DEFAULT 'pending',attempts INTEGER NOT NULL DEFAULT 0,last_error TEXT,created_at TEXT NOT NULL,processed_at TEXT,UNIQUE(provider,external_id));
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS runtime_nodes (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,name TEXT NOT NULL,slug TEXT NOT NULL,kind TEXT NOT NULL DEFAULT 'computer',status TEXT NOT NULL DEFAULT 'offline',endpoint TEXT,capabilities_json TEXT NOT NULL DEFAULT '{}',host_info_json TEXT NOT NULL DEFAULT '{}',storage_root TEXT NOT NULL,agent_version TEXT,last_seen_at TEXT,token_hash TEXT,labels_json TEXT NOT NULL DEFAULT '{}',is_shared INTEGER NOT NULL DEFAULT 0,created_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(tenant_id,slug));
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS workspace_migrations (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,space_id TEXT NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,source_node_id TEXT NOT NULL REFERENCES runtime_nodes(id),target_node_id TEXT NOT NULL REFERENCES runtime_nodes(id),status TEXT NOT NULL DEFAULT 'pending',phase TEXT,progress_pct INTEGER NOT NULL DEFAULT 0,message TEXT,manifest_json TEXT,archive_path TEXT,archive_size TEXT,archive_sha256 TEXT,exclude_patterns_json TEXT NOT NULL DEFAULT '[]',source_retained INTEGER NOT NULL DEFAULT 0,error TEXT,started_at TEXT,completed_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS space_projects (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,space_id TEXT NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,slug TEXT NOT NULL,name TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',instructions TEXT NOT NULL DEFAULT '',has_workspace INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(space_id,slug));
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS mcp_store_sources (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,name TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',source_url TEXT NOT NULL,format TEXT NOT NULL DEFAULT 'auto',manifest_json TEXT NOT NULL DEFAULT '{}',servers_json TEXT NOT NULL DEFAULT '[]',enabled INTEGER NOT NULL DEFAULT 1,fetched_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(tenant_id,source_url));
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS store_catalog_entries (id TEXT PRIMARY KEY,tenant_id TEXT,source_id TEXT NOT NULL,kind TEXT NOT NULL,ref TEXT NOT NULL,name TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',meta_json TEXT NOT NULL DEFAULT '{}',updated_at TEXT NOT NULL);
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS platform_skill_repos (id TEXT PRIMARY KEY,repo_key TEXT NOT NULL UNIQUE,provider TEXT NOT NULL DEFAULT 'github',source_json TEXT NOT NULL DEFAULT '{}',ref TEXT,version TEXT,upstream_etag TEXT,packages_json TEXT NOT NULL DEFAULT '[]',partial INTEGER NOT NULL DEFAULT 0,skill_count INTEGER NOT NULL DEFAULT 0,size_bytes INTEGER NOT NULL DEFAULT 0,warnings_json TEXT NOT NULL DEFAULT '[]',checked_at TEXT NOT NULL,fetched_at TEXT NOT NULL,ref_count INTEGER NOT NULL DEFAULT 0,last_error TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS skill_source_tokens (id TEXT PRIMARY KEY,scope_key TEXT NOT NULL,provider TEXT NOT NULL DEFAULT 'github',token_enc TEXT NOT NULL,label TEXT,hint TEXT,last_used_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(scope_key,provider));
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS tool_call_logs (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,api_key_id TEXT REFERENCES api_keys(id) ON DELETE SET NULL,agent_id TEXT REFERENCES agents(id) ON DELETE SET NULL,qualified_name TEXT NOT NULL,local_name TEXT NOT NULL,provider_id TEXT NOT NULL DEFAULT '',instance_id TEXT,args_json TEXT NOT NULL DEFAULT '{}',result_json TEXT NOT NULL DEFAULT '',is_error INTEGER NOT NULL DEFAULT 0,duration_ms INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL);
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS agent_bindings (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,space_id TEXT NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,agent_id TEXT REFERENCES agents(id) ON DELETE SET NULL,instance_id TEXT NOT NULL REFERENCES component_instances(id) ON DELETE CASCADE,created_at TEXT NOT NULL,UNIQUE(space_id,instance_id));
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS agent_channel_bindings (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,space_id TEXT NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,agent_id TEXT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,platform TEXT NOT NULL,profile_key TEXT NOT NULL,label TEXT NOT NULL DEFAULT '',enabled INTEGER NOT NULL DEFAULT 0,settings_json TEXT NOT NULL DEFAULT '{}',config_enc TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS agent_channel_threads (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,binding_id TEXT NOT NULL REFERENCES agent_channel_bindings(id) ON DELETE CASCADE,session_id TEXT NOT NULL REFERENCES cloud_agent_sessions(id) ON DELETE CASCADE,external_thread_key TEXT NOT NULL,external_user_key TEXT,last_event_id TEXT,last_event_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(binding_id,external_thread_key));
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS agent_channel_events (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,binding_id TEXT NOT NULL REFERENCES agent_channel_bindings(id) ON DELETE CASCADE,external_event_id TEXT NOT NULL,received_at TEXT NOT NULL,UNIQUE(binding_id,external_event_id));
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS zakurabot_files (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,device_id TEXT NOT NULL,binding_id TEXT NOT NULL REFERENCES agent_channel_bindings(id) ON DELETE CASCADE,agent_id TEXT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,path TEXT NOT NULL,name TEXT NOT NULL,mime TEXT NOT NULL,size INTEGER NOT NULL,created_at TEXT NOT NULL);
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS zakurabot_interactions (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,device_id TEXT NOT NULL,binding_id TEXT NOT NULL REFERENCES agent_channel_bindings(id) ON DELETE CASCADE,agent_id TEXT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,session_id TEXT NOT NULL REFERENCES cloud_agent_sessions(id) ON DELETE CASCADE,run_id TEXT,source_session_id TEXT NOT NULL REFERENCES cloud_agent_sessions(id) ON DELETE CASCADE,source_run_id TEXT,request_id TEXT NOT NULL,type TEXT NOT NULL,payload_json TEXT NOT NULL,reply_to TEXT,status TEXT NOT NULL DEFAULT 'pending',claimed_at TEXT,event_seq INTEGER NOT NULL,created_at TEXT NOT NULL);
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS zakurabot_messages (id TEXT PRIMARY KEY,seq INTEGER NOT NULL,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,device_id TEXT NOT NULL,binding_id TEXT NOT NULL REFERENCES agent_channel_bindings(id) ON DELETE CASCADE,agent_id TEXT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,client_message_id TEXT,frame_json TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(device_id,binding_id,agent_id,client_message_id));
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS file_shares (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,agent_id TEXT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,token_hash TEXT NOT NULL UNIQUE,path TEXT NOT NULL,file_name TEXT NOT NULL,mime_type TEXT,size_bytes INTEGER,status TEXT NOT NULL DEFAULT 'active',ttl_minutes INTEGER NOT NULL,expires_at TEXT NOT NULL,download_count INTEGER NOT NULL DEFAULT 0,disposition TEXT NOT NULL DEFAULT 'attachment',revoked_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS managed_containers (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,instance_id TEXT REFERENCES component_instances(id) ON DELETE SET NULL,space_id TEXT REFERENCES spaces(id) ON DELETE CASCADE,agent_id TEXT REFERENCES agents(id) ON DELETE SET NULL,docker_id TEXT,name TEXT NOT NULL,image TEXT NOT NULL,purpose TEXT NOT NULL DEFAULT 'component',status TEXT NOT NULL DEFAULT 'created',labels_json TEXT NOT NULL DEFAULT '{}',ports_json TEXT NOT NULL DEFAULT '[]',env_enc TEXT,allocated_to TEXT,runtime_node_id TEXT REFERENCES runtime_nodes(id) ON DELETE SET NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
