CREATE TABLE IF NOT EXISTS email_connector_instances (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,name TEXT NOT NULL,product TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 0,config_enc TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS message_reactions (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,device_id TEXT NOT NULL,binding_id TEXT NOT NULL REFERENCES agent_channel_bindings(id) ON DELETE CASCADE,agent_id TEXT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,message_id TEXT NOT NULL,user_id TEXT NOT NULL,emoji TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(tenant_id,device_id,binding_id,agent_id,message_id,user_id));
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS model_catalog_entries (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,source TEXT NOT NULL,provider_id TEXT NOT NULL,provider_name TEXT NOT NULL,model_id TEXT NOT NULL,name TEXT NOT NULL,meta_json TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(tenant_id,source,provider_id,model_id));
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS network_audit_logs (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,actor_type TEXT NOT NULL,actor_id TEXT,action TEXT NOT NULL,target_type TEXT,target_id TEXT,detail_json TEXT NOT NULL DEFAULT '{}',ip TEXT,created_at TEXT NOT NULL);
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS network_integrations (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,kind TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'disconnected',display_name TEXT,credentials_enc TEXT NOT NULL DEFAULT '{}',meta_json TEXT NOT NULL DEFAULT '{}',last_sync_at TEXT,last_error TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(tenant_id,kind));
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS network_security_policies (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,scope TEXT NOT NULL DEFAULT 'tenant',enabled INTEGER NOT NULL DEFAULT 1,exposure_enabled INTEGER NOT NULL DEFAULT 1,default_ttl_minutes INTEGER NOT NULL DEFAULT 60,max_ttl_minutes INTEGER NOT NULL DEFAULT 1440,max_active_per_agent INTEGER NOT NULL DEFAULT 3,max_active_per_tenant INTEGER NOT NULL DEFAULT 50,denied_ports_json TEXT NOT NULL DEFAULT '[22,2375,2376,5432,6379,27017,5900,6080,9222,8787,7443]',allow_desktop_exposure INTEGER NOT NULL DEFAULT 0,allow_public_exposure INTEGER NOT NULL DEFAULT 1,allow_tcp_exposure INTEGER NOT NULL DEFAULT 0,agents_can_expose INTEGER NOT NULL DEFAULT 1,require_user_approval INTEGER NOT NULL DEFAULT 0,require_tailscale_for_remote_runners INTEGER NOT NULL DEFAULT 0,audit_retention_days INTEGER NOT NULL DEFAULT 90,updated_by TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(tenant_id,scope));
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS oauth_identities (id TEXT PRIMARY KEY,provider TEXT NOT NULL,provider_user_id TEXT NOT NULL,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,profile_json TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(provider,provider_user_id));
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS oauth_login_states (id TEXT PRIMARY KEY,provider TEXT NOT NULL,code_verifier TEXT NOT NULL,expires_at TEXT NOT NULL,created_at TEXT NOT NULL);
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS platform_service_quotas (id TEXT PRIMARY KEY,scope_key TEXT NOT NULL,service_key TEXT NOT NULL,monthly_limit INTEGER,daily_limit INTEGER,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(scope_key,service_key));
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS platform_service_usage (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,user_id TEXT NOT NULL DEFAULT '',service_key TEXT NOT NULL,period TEXT NOT NULL,request_count INTEGER NOT NULL DEFAULT 0,error_count INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(tenant_id,user_id,service_key,period));
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS platform_services (id TEXT PRIMARY KEY,service_key TEXT NOT NULL UNIQUE,mode TEXT NOT NULL DEFAULT 'disabled',desired_state TEXT NOT NULL DEFAULT 'stopped',status TEXT NOT NULL DEFAULT 'stopped',health_status TEXT NOT NULL DEFAULT 'unknown',config_enc TEXT NOT NULL DEFAULT '{}',endpoint_url TEXT,containers_json TEXT NOT NULL DEFAULT '[]',last_error TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS port_exposures (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,agent_id TEXT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,runtime_node_id TEXT REFERENCES runtime_nodes(id) ON DELETE SET NULL,name TEXT,port INTEGER NOT NULL,protocol TEXT NOT NULL DEFAULT 'http',provider TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'starting',public_url TEXT,relay_host TEXT,relay_port INTEGER,integration_id TEXT REFERENCES network_integrations(id) ON DELETE SET NULL,ttl_minutes INTEGER,expires_at TEXT,last_error TEXT,created_by_type TEXT,created_by_id TEXT,stopped_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS scim_user_mappings (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,external_id TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(tenant_id,external_id),UNIQUE(tenant_id,user_id));
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS sso_login_states (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,protocol TEXT NOT NULL,code_verifier TEXT,nonce TEXT,expires_at TEXT NOT NULL,created_at TEXT NOT NULL);
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS tenant_content_cleanup_jobs (id TEXT PRIMARY KEY,idempotency_key TEXT NOT NULL UNIQUE,tenant_id TEXT NOT NULL,action TEXT NOT NULL,payload_json TEXT NOT NULL DEFAULT '{}',status TEXT NOT NULL DEFAULT 'pending',attempts INTEGER NOT NULL DEFAULT 0,max_attempts INTEGER NOT NULL DEFAULT 8,available_at TEXT NOT NULL,locked_at TEXT,locked_by TEXT,last_error TEXT,completed_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS tunnel_provider_settings (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,provider TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 0,is_default INTEGER NOT NULL DEFAULT 0,config_enc TEXT NOT NULL DEFAULT '{}',last_test_at TEXT,last_test_ok INTEGER,last_error TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(tenant_id,provider));
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS upstream_oauth_clients (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,mcp_url TEXT NOT NULL,host TEXT NOT NULL,client_id TEXT NOT NULL,secret_enc TEXT,client_name TEXT NOT NULL DEFAULT '',source TEXT NOT NULL,registration_endpoint TEXT,scope TEXT NOT NULL DEFAULT '',instance_id TEXT REFERENCES component_instances(id) ON DELETE SET NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(tenant_id,host,client_id));
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS user_recovery_codes (id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,code_hash TEXT NOT NULL,used_at TEXT,created_at TEXT NOT NULL);
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS user_totp (user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,secret_enc TEXT NOT NULL,enabled_at TEXT,created_at TEXT NOT NULL);
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS user_usage_daily (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,day TEXT NOT NULL,logins INTEGER NOT NULL DEFAULT 0,sessions_started INTEGER NOT NULL DEFAULT 0,runs_ok INTEGER NOT NULL DEFAULT 0,runs_error INTEGER NOT NULL DEFAULT 0,tool_calls INTEGER NOT NULL DEFAULT 0,tool_errors INTEGER NOT NULL DEFAULT 0,duration_ms INTEGER NOT NULL DEFAULT 0,last_seen_at TEXT,UNIQUE(tenant_id,user_id,day));
